### PR TITLE
Code formatting fixes.

### PR DESCRIPTION
**Pull request by cosmicdreams**
Hey @mlsamuelson can we open a discussion about HaxModeController.  It is both extending NodeViewController and not really overriding any of the base class's methods.

### CODE REVIEW

**Comment by cosmicdreams** [comment]
This fixes all but 3 Drupal coding standards violations.

**Review by mlsamuelson — COMMENTED** [review]
Reviewed formatting fixes. Looks good. Thx @cosmicdreams! Will test in the morning and if all checks out, will merge.

**Comment by mlsamuelson** [comment]
This, as a solution, results in a Max Execution Time error. The nested calls to $this->t() , I'm thinking.

`        '#description' => $this->t('See @description for details.', [
          '@description' => Link::fromTextAndUrl($this->t('@name developer docs',
            ['@name' => $app['name']]), Url::fromUri($app['docs'])),
        ]),`

**Comment by mlsamuelson** [comment]
This fixes it.  I'm going to merge your pull request (which otherwise checks out), and then will apply this. 
`
diff --git a/src/Form/HaxSettings.php b/src/Form/HaxSettings.php
index 71b06ca..e97e1b0 100644
--- a/src/Form/HaxSettings.php
+++ b/src/Form/HaxSettings.php
@@ -6,6 +6,7 @@ use Drupal\Core\Form\ConfigFormBase;
 use Drupal\Core\Form\FormStateInterface;
 use Drupal\Core\Link;
 use Drupal\Core\Render\Element;
+use Drupal\Core\Url;
 use Drupal\hax\HaxService;

 /**
@@ -72,10 +73,8 @@ class HaxSettings extends ConfigFormBase {
           '@name' => $app['name'],
         ]),
         '#default_value' => $config->get('hax_' . $key . '_key'),
-        '#description' => $this->t('See @description for details.', [
-          // @todo: Link::fromTextAndUrl is missing a required parameter.
-          '@description' => Link::fromTextAndUrl($this->t('@name developer docs', ['@name' => $app['name']])),
-        ]),
+        '#description' => Link::fromTextAndUrl($this->t('See @name developer docs',
+          ['@name' => $app['name']]), Url::fromUri($app['docs'])),
       ];
     }
`

**Pull request merged**
